make date-check more easy to use
rust-lang/rustc-dev-guide pull request #1428
Opened 2022-08-14 07:13 UTC by tshepang

One could not run it like the following, for the would be a panic:

    cargo run --manifest-path ci/date-check/Cargo.toml .

2022-08-14 13:51 UTC, jyn514 requested changes
Rather than removing this functionality altogether, can you make `root_dir` using CARGO_MANIFEST_PATH or something like that? Or use `unwrap_or` instead of unwrap?

2022-08-14 14:31 UTC, tshepang commented
thanks for the suggestion... didn't notice I made some things less pretty

2022-08-17 15:57 UTC, camelid requested changes

2022-08-17 15:57 UTC, camelid commented on ci/date-check/src/main.rs
> +    let root_dir = env::args().nth(1).unwrap_or(".".into());
I'd rather not make this change because then people doing `cargo run` in date-check's directory will get weird results and not realize why.

2022-08-24 02:28 UTC, jyn514 approved these changes

2022-08-26 02:56 UTC, camelid approved these changes
Thanks!

2022-08-26 02:56 UTC, merged