Improve documentation of MIR queries & passes
rust-lang/rustc-dev-guide pull request #1434
Opened 2022-08-16 11:32 UTC by Jaic1

This PR improve the documentation of MIR queries and passes.

Below is the summary of changes:
- delete `mir_validated`
- add `mir_promoted`, `mir_drops_elaborated_and_const_checked`, `optimized_mir`
- replace the `NoLandingPads` pass example with `CleanupNonCodegenStatements`
- extend the stealing mechanism and give the dependency of MIR queries as an overview
- add `mdbook-mermaid` in the build instructions

FIXME:
- Does `ty::queries::foo::force(...)` still appear in rustc?

Since rust-lang/rust#99102 may significantly change the MIR queries (and thus its doc), we can wait for its result or send follow-up PRs. This is mostly documenting the code in `rustc_mir_transform`, so maybe cc @rust-lang/wg-mir-opt.

2022-08-22 06:37 UTC, tshepang commented on src/mir/passes.md
> +that you do not accidently read from these intermediate queries without
```suggestion
that you do not accidentally read from these intermediate queries without
```

2022-08-22 07:16 UTC, Jaic1 commented on src/mir/passes.md
> +that you do not accidently read from these intermediate queries without
thanks, will fix it

2022-08-31 05:27 UTC, tshepang commented
with https://github.com/rust-lang/rust/pull/99102 now accepted, does this need to change

2022-09-05 06:51 UTC, Jaic1 commented
Yes, the doc in this PR need to change to reflect the recent changes in [rust-lang/rust#99102](https://github.com/rust-lang/rust/pull/99102). But we could wait a minute until it gets more stable and complete since the MIR phases and semantics there, I think, are under overhaul.

2023-01-01 00:25 UTC, jyn514 commented
https://github.com/rust-lang/rust/pull/99102 has been merged :)

2023-02-09 10:14 UTC, JohnTitor commented
@oli-obk Could you help with the review here or ping relevant folks?
@Jaic1 Could you resolve the merge conflict meanwhile?

2023-02-09 13:43 UTC, oli-obk requested changes

2023-02-09 13:43 UTC, oli-obk commented on src/mir/passes.md
> +- for a function - you can use the `optimized_mir(def_id)` query;
there's also the MIR that const eval sees for a function: `mir_for_ctfe(def_id)`

2023-02-09 13:43 UTC, oli-obk commented
cc @JakobDegen

2023-10-26 14:21 UTC, spastorino commented
I'm not sure what's the current status of this PR, but would be great if we merge something about it, thoughts?.

2024-06-30 03:07 UTC, Jaic1 commented
Sorry for the late reply, I had been busy with my master project for the last few years.

I just refined the MIR passes doc and resolved the git conflicts.

2024-06-30 03:10 UTC, Jaic1 commented
cc @spastorino, could you help me find some reviewers?

2024-07-09 08:05 UTC, oli-obk approved these changes

2024-07-09 08:06 UTC, oli-obk commented
Please rebase so there are no more merge commits

2024-07-10 05:53 UTC, Jaic1 commented
> Please rebase so there are no more merge commits

Done.

2024-07-10 22:38 UTC, spastorino approved these changes
Looks good to me but I'd leave the merge up to @oli-obk who knows better about MIR than me.

2024-07-15 15:16 UTC, merged